# Dockerfile
# Layer 1: Utilisation d'une image php:7.2-apache pour la base du container.
FROM php:7.2-apache

# Layer 2: Copier le contenu de l'app `src` dans le dossier /var/www/html du container
COPY src/ /var/www/html/
