version: '3'

services: 
    frontend:
        container_name: frontend 
        build: 
            context: frontend/
        image: frontend-image
        ports:
            - 3000:3000
        command: npm start
        volumes:
            - ./frontend/:/usr/app
            - /usr/app/node_modules
        depends_on:
            - server 
    server:
        container_name: server
        build:
            context: server/
        image: backend-image 
        ports:
            - 5000:5000  
        volumes:
            - ./server/:/usr/src/app
            - /usr/src/app/node_modules  
        depends_on:
            - mongo
        environment:
            - NODE_ENV=development
        networks:
            - app-network
    mongo:
        image: mongo
        volumes:
            - data-volume:/data/db
        ports:
            - 3500:3500
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules: